//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyerFærdig.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bruger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bruger()
        {
            this.Lobby1 = new HashSet<Lobby>();
        }
    
        public int ID { get; set; }
        public string Fornavn { get; set; }
        public string Efternavn { get; set; }
        public string Username { get; set; }
        public string E_mail { get; set; }
        public string password { get; set; }
        public Nullable<int> Lobby_ID { get; set; }
    
        public virtual Lobby Lobby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lobby> Lobby1 { get; set; }
    }
}
