//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meyer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sandsynlighed
    {
        public int Kast { get; set; }
        public decimal Sandsynlighed1 { get; set; }
    }
}
